### PR TITLE
update dependent libraries

### PR DESCRIPTION
**Pull request by firewood**
- ImageMagick 6: 6.9.11-43 to 6.9.12-14
    - There seems no destructive changes in ChangeLog. https://github.com/ImageMagick/ImageMagick6/blob/main/ChangeLog
- libheif: 1.6.2 to 1.12.0
    - There seems no destructive changes. https://github.com/strukturag/libheif/releases
- Golang: 1.14.1 to 1.14.15

### CODE REVIEW

**Comment by elrob** [comment]
Maybe you should do a quick test for a heif conversion with the image before and after this update to check there's nothing strangely different?

**Comment by firewood** [comment]
Sure! I'll try to create a quick regression test.

**Comment by firewood** [comment]
@elrob I've created a quick regression test and ran it. Though the binary files are different, I don't see any significant difference.

Because we don't specify versions to some libraries (e.g., libpng), the binary file might be different.

script: https://github.com/smartnews/yoya-thumber/pull/42/files
result:
```
images/full-moon-11287159978joRe.jpg: OK
images/full-moon-11287159978joRe-prd.png images/full-moon-11287159978joRe-local.png differ: char 125, line 3
images/full-moon-11287159978joRe.png: FAILED
images/full-moon-11287159978joRe.webp: OK
images/full-moon-11287159978joRe-prd.heif images/full-moon-11287159978joRe-local.heif differ: char 4, line 1
images/full-moon-11287159978joRe.heif: FAILED
images/1-12106831258yNO.jpg: OK
images/1-12106831258yNO-prd.png images/1-12106831258yNO-local.png differ: char 146, line 3
images/1-12106831258yNO.png: FAILED
images/1-12106831258yNO.webp: OK
images/1-12106831258yNO-prd.heif images/1-12106831258yNO-local.heif differ: char 28, line 1
images/1-12106831258yNO.heif: FAILED
```
(the script will remove the same files and keep different files)

**Comment by firewood** [comment]
I found the updated version can handle odd-size images properly.
original size: 1280 x 853
HEIC (production): 1280 x 852
HEIC (new): 1280 x 853

**Comment by elrob** [comment]
Cool. I think just checking that the output file sizes are similar before and after and the images look the same to human eye is fine. 👍

**Comment by elrob** [comment]
@firewood san, maybe we can close this PR now as we're no longer using yoya-thumber.

**Comment by firewood** [comment]
Sure, let's close it for now.

**Pull request closed without merging**
